### ISSUE TITLE
How to handle optional fields?

### ISSUE THREAD

**Issue by ArthurClemens** [elixir-cldr/cldr_trans#7]
Perhaps this is more of an Ecto question, but I haven't found the answer.

I have an Article with fields `title` and `body`, of which only `title` is required. The `Translations` struct lists both field keys - if the translation for `body` is empty, the changeset is marked invalid.

What I would like to achieve is that this struct is accepted:
```elixir
translations: %MyApp.Article.Translations{
  en: %MyApp.Article.Translations.Fields{
    title: "Hello world!",
    body: ""
  }
}
```

**Comment by kipcole9** [comment]
You're right, the definition of the embedded schema that is automatically generated also [generates a changeset](https://github.com/elixir-cldr/cldr_trans/blob/main/lib/cldr_trans.ex#L241-L264) the has `validate_required/2` for all translatable fields.

I think I can modify the api to allow a list of translatable fields and some way to flag if required or not required. I need to keep the API consistent so it's not a breaking change.

How about something like:
```elixir
use MyApp.Cldr.Trans, translates: [:title, :body], required: [:title]
```
If the `:required` option isn't specified, all translations are required (current behaviour).

An additional idea might be to allow a validation callback to be configured so it might be:
```elixir
use MyApp.Cldr.Trans, translates: [:title, :body], required: [:title], validate_change: &MyModule.validate/1
```

Thoughts?

BTW,  if this is urgent you can handcraft the embedded schema and not use the `translations/1` macro - then you can do whatever you want.  The readme shows you what the structure would look like.

**Comment by kipcole9** [comment]
I don't know what the ramifications are in the rest of the library if a translation is missing - that will need some extensive testing to ensure no unexpected behaviour too.

**Comment by kipcole9** [comment]
Another option is to not change the current behaviour at all. This would mean that if you want different behaviour you would write your own changeset for the translations embedded schema and then `cast_embedded(:translations, MyTranslation)` in the main schema changeset.

**Comment by ArthurClemens** [comment]
Thanks for your swift reply.

Some thoughts:
- I've placed changeset functions separately from schemas, so it is not logical to define required fields in the schema module with the extended `required` option.
- I prefer the direction of writing a custom changeset

**Comment by kipcole9** [comment]
> I prefer the direction of writing a custom changeset

Then apart from updating the documentation to note that the generated changeset includes `:required` on all translatable fields, there is nothing to be done?

I agree with you, I think suggesting that library users write their own changesets is the better approach.

**Comment by ArthurClemens** [comment]
It's not obvious to me how to override the default changeset.

**Comment by kipcole9** [comment]
And I'm exposing my lack of knowledge in how Ecto changesets work with embedded schemas. 😀

I though embedded schema changesets are invoked with the 'cast_embed/2' call and is there explicit.  Does it happen implicitly as well?

**Comment by ArthurClemens** [comment]
After a bit of playing around, it appears to be quite easy to override the default changeset. So no need to implement custom embeds.

Using a custom `translation_field_changeset` function I can define the validation behaviour:

```elixir
defp changeset(article, attrs) do
  article
  |> cast(attrs, [
    :title,
    :body,
  ])
  |> cast_embed(:translations, with: &translations_changeset/2)
  |> validate_required([:title])
end

defp translations_changeset(translations, params) do
  translations
  |> cast(params, [])
  |> cast_embed(:en, with: &translation_field_changeset/2)
end

defp translation_field_changeset(schema, params) do
  schema
  |> cast(params, [:title, :body])
  |> validate_required([:title])
end
```

**Comment by kipcole9** [comment]
You make a good point, the documentation needs improving and I'll work on that.  I think for your example, it can be slightly simpler to do the following:

```elixir
defmodule MyApp.Article do
  use Ecto.Schema
  use MyApp.Cldr.Trans, translates: [:title, :body]

  schema "articles" do
    field :title, :string
    field :body, :string
    translations :translations
  end
end
```
Then use your changeset functions in your repo as you are already doing:
```elixir
defmodule MyApp.Repo do
  defp changeset(article, attrs) do
    article
    |> cast(attrs, [
      :title,
      :body,
    ])
    |> cast_embed(:translations, with: &translations_changeset/2)
    |> validate_required([:title])
  end

  defp translations_changeset(translations, params) do
    translations
    |> cast(params, [])
    |> cast_embed(:en, with: &translation_field_changeset/2)
  end

  defp translation_field_changeset(schema, params) do
    schema
    |> cast(params, [:title, :body])
    |> validate_required([:title])
  end
end
```
Does that work as expected?

**Comment by ArthurClemens** [comment]
Yes, I already updated my comment above.

**Comment by kipcole9** [comment]
Thanks for the feedback. I'll leave the issue open until I update the docs in the next 48 hours.

**Comment by kipcole9** [comment]
I believe the updated docs (now published to [hexdocs](https://hexdocs.pm/ex_cldr_trans) improve the discussion around this area. I will close for now - but I would warmly welcome further feedback and PRs to make the docs even better.
